Added support to watch uploads
SpaceOgre/TwitchMod.bundle pull request #1
Opened 2017-04-23 22:46 UTC by r-gruber

Twitch added a possibilty to upload videos a while ago. VODs can now
either be of type highlight, archive or upload. In order to be able
to see them the query must use the new 'broadcast_type' parameter.

This plugin will now display all uploads of a channel in a sepate list
similar to how it was done so far for past broadcasts or highlights.

2017-04-24 19:45 UTC, SpaceOgre requested changes
Hi, 

Thanks for the commit :) 

I think it would make more sense to change broadcast and upload parameters to just use broadcastType for the ChannelVodList straight away. Less mapping needed.

2017-04-29 20:44 UTC, r-gruber commented
I replaced the boolean parameters of the ChannelVodList method with a single broadcastType parameter. The used broadcastType will also be used to determine the correct title of the page.

2017-04-29 20:52 UTC, SpaceOgre approved these changes

2017-04-29 20:55 UTC, SpaceOgre requested changes

2017-04-29 20:55 UTC, SpaceOgre commented on Contents/Code/__init__.py
>  @route(PREFIX + '/channel/vods', broadcasts=bool, uploads=bool, limit=int)
You forgot to change the route parameters,

2017-04-29 20:56 UTC, SpaceOgre commented
Except the route parameters it looks great :) 
Will merge when it is fixed.

2017-04-30 18:16 UTC, SpaceOgre commented
Thanks for your contribution :)

2017-04-30 18:16 UTC, merged